global:
  resolve_timeout: 5m
  smtp_from: 'alertmanager@incontrol.local'
  smtp_smarthost: 'localhost:25'
  smtp_require_tls: false

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'email-notifications'
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: 'email-notifications'
      repeat_interval: 4h

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: '{{ .GroupLabels.email }}'
        send_resolved: true
        headers:
          subject: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        html: |
          <h1>{{ .Status | toUpper }}</h1>
          <h2>{{ .GroupLabels.alertname }}</h2>
          <p><strong>Instance:</strong> {{ .GroupLabels.instance }}</p>
          <p><strong>Severity:</strong> {{ .GroupLabels.severity }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
          <p><strong>Started:</strong> {{ .StartsAt }}</p>
          {{ if eq .Status "resolved" }}
          <p><strong>Resolved:</strong> {{ .EndsAt }}</p>
          {{ end }} 