global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'incontrol'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000']
    
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
    
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['localhost:9121']
    
  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['localhost:9104'] 